### ISSUE TITLE
Relax hyphens checking

### ISSUE THREAD

**Issue by gotson** [SaekiTominaga/isbn-verify#2]
The hyphen check is too strict.

For example on Amazon, ISBN 13 would be displayed like: `978-2205043754`. This would not pass the check.

This prevents copy/pasting values into text fields.

Would it be possible to have an option to ignore hyphens, anywhere in the string?

**Comment by SaekiTominaga** [comment]
Hello, @gotson.
In non-strict mode, changed to relax the hyphen restriction.

- 🆗 9782205043754
- 🆗 978-2205043754
- 🆖 9782205043754- (Hyphen at the end)
- 🆖 978--2205043754 (Hyphens are continuous)

\* The behavior of strict mode remains the same as before. All of the above examples will be invalid.

**Comment by SaekiTominaga** [comment]
Released as [v1.3.0](https://www.npmjs.com/package/@saekitominaga/isbn-verify/v/1.3.0).
