### ISSUE TITLE
[Module not found: Error] build in react

### ISSUE THREAD

**Issue by douglaszaltron** [SaekiTominaga/isbn-verify#3]
i have this problem when running the build in a react project. can you tell me a solution for me to apply?

Module not found: Error: Can't resolve '/home/douglaszaltron/node_modules/@babel/runtime/helpers/esm/classCallCheck' in '/home/douglaszaltron/node_modules/@saekitominaga/isbn-verify/dist'
Did you mean 'classCallCheck.js'?
BREAKING CHANGE: The request '/home/douglaszaltron/node_modules/@babel/runtime/helpers/esm/classCallCheck' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by douglaszaltron** [comment]
solution: remove "type": "module" in package.json

**Comment by SaekiTominaga** [comment]
Hello, @douglaszaltron
I don't know the details of your project, but I don't think it's a problem with React itself.
I have confirmed that it works fine with React project created with `create-react-app`.

App.js
```JavaScript
import IsbnVerify from "@saekitominaga/isbn-verify";

function App() {
  const isbnVerify = new IsbnVerify("978-4-06-519981-0");

  return (
    <div className="App">
      <dl>
        <dt>isValid()</dt>
        <dd>{String(isbnVerify.isValid())}</dd>
        <dt>isIsbn10()</dt>
        <dd>{String(isbnVerify.isIsbn10())}</dd>
        <dt>isIsbn13()</dt>
        <dd>{String(isbnVerify.isIsbn13())}</dd>
      </dl>
    </div>
  );
}

export default App;
```
![react](https://user-images.githubusercontent.com/4138486/135020300-c7718ea1-8e80-454a-a117-dd8e89650a60.png)

- This feature is assumed to work with ES Modules. (It is not possible to remove `"type": "module"` from package.json.
- If you want to make it work with CommonJS, please take care of it by yourself. (I'm developing this alone, and I don't have the capacity to provide support for CommonJS.)
- Please continue to comment if the problem is not with CommonJS / ES Modules or with your React project configuration, but with the program or configuration of this feature.

**Comment by douglaszaltron** [comment]
@SaekiTominaga I am using the "react-scripts": "5.0.0-next.37" as the webpack 5, it might be something involving this then.

**Comment by SaekiTominaga** [comment]
In the following example, webpack is not used, but it works fine with `react-scripts@5.0.0-next.37`.
This is probably a problem with your project settings, so please review your settings.
If you think there is a problem with the configuration of this feature, please show me the specific configuration and source code of your project.

```
npm i react-dom react-scripts@5.0.0-next.37 @saekitominaga/isbn-verify`
npm start
```

public/index.html
```html
<!DOCTYPE html>
<html>
<head>
<title>test</title>
</head>
<body>
<div id="root"></div>
</body>
</html>
```

src/index.js
```JavaScript
import ReactDOM from "react-dom";
import IsbnVerify from "@saekitominaga/isbn-verify";

const isbnVerify = new IsbnVerify("978-4-06-519981-0");

ReactDOM.render(
  <dl>
    <dt>isValid()</dt>
    <dd>{String(isbnVerify.isValid())}</dd>
    <dt>isIsbn10()</dt>
    <dd>{String(isbnVerify.isIsbn10())}</dd>
    <dt>isIsbn13()</dt>
    <dd>{String(isbnVerify.isIsbn13())}</dd>
  </dl>,
  document.getElementById("root")
);
```

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "start": "react-scripts start"
  },
  "dependencies": {
    "@saekitominaga/isbn-verify": "^1.4.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^5.0.0-next.37"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
